// Ambient declaration for the build-time virtual module generated by
// vite-plugin-agent-ui.js (registers agent UI packages from ma-config.toml).
// Side-effect only — imported once from +layout.svelte.
declare module "virtual:agent-ui";
