use std::fs;
use std::path::Path;

use toml_edit::{Array, DocumentMut, InlineTable, Item, Table, Value};

use crate::config::{AgentEntry, AgentSource, BuildConfig, DepConfig};
use crate::registry::{self, Registry};

/// Update `src-tauri/Cargo.toml` with the selected agents as dependencies.
pub fn update_cargo_toml(
    config: &BuildConfig,
    registry: &Registry,
    tauri_root: &Path,
) -> Result<(), String> {
    let cargo_path = tauri_root.join("Cargo.toml");
    let original =
        fs::read_to_string(&cargo_path).map_err(|e| format!("Failed to read Cargo.toml: {e}"))?;

    // Backup
    backup_file(&cargo_path)?;

    let mut doc: DocumentMut = original
        .parse()
        .map_err(|e| format!("Failed to parse Cargo.toml: {e}"))?;

    // Update dependencies
    update_dependencies(&mut doc, config, registry)?;

    // Local overrides go into [patch] so [dependencies] keeps canonical sources
    update_patch_section(&mut doc, config, registry);

    fs::write(&cargo_path, doc.to_string()).map_err(|e| format!("Failed to write Cargo.toml: {e}"))
}

/// Generate `src-tauri/src/agents.rs` with imports for each agent.
pub fn generate_agents_rs(config: &BuildConfig, tauri_root: &Path) -> Result<(), String> {
    let agents_path = tauri_root.join("src/agents.rs");

    let mut content = String::from(
        "//! Agent crate imports (auto-generated by ma-config, do not edit)\n\
         //!\n\
         //! Each `use` pulls in the crate, causing #[modular_agent] registrations\n\
         //! to be linked via the `inventory` crate.\n",
    );

    for agent in &config.agents {
        let crate_name = agent.rust_crate_name();
        content.push_str(&format!("\nuse {crate_name} as _;\n"));
    }

    fs::write(&agents_path, content).map_err(|e| format!("Failed to write agents.rs: {e}"))
}

fn update_dependencies(
    doc: &mut DocumentMut,
    config: &BuildConfig,
    registry: &Registry,
) -> Result<(), String> {
    let deps = doc["dependencies"]
        .as_table_mut()
        .ok_or("Missing [dependencies] in Cargo.toml")?;

    // Remove all modular-agent-* and tauri-plugin-modular-agent deps
    let keys_to_remove: Vec<String> = deps
        .iter()
        .filter_map(|(key, _)| {
            if key.starts_with("modular-agent-") || key == "tauri-plugin-modular-agent" {
                Some(key.to_string())
            } else {
                None
            }
        })
        .collect();

    for key in keys_to_remove {
        deps.remove(&key);
    }

    // Add core — always as version in [dependencies].
    // Path/Git override goes into [patch.crates-io].
    // The desktop app embeds the flow-editing MCP server (toggled at runtime
    // via Core Settings), so the "mcp-server" feature is always required.
    let mut core_dep = InlineTable::new();
    core_dep.insert("version", dep_config_to_dep_value(&config.core));
    let mut core_features = Array::new();
    core_features.push("mcp-server");
    core_dep.insert("features", Value::from(core_features));
    deps.insert(
        "modular-agent-core",
        Item::Value(Value::InlineTable(core_dep)),
    );

    // Add plugin — same strategy as core.
    deps.insert(
        "tauri-plugin-modular-agent",
        Item::Value(dep_config_to_dep_value(&config.plugin)),
    );

    // Add selected agents. A local path for a known agent is expressed as the
    // canonical git URL here plus a [patch] entry, so reverting to the
    // canonical source only requires deleting the patch section.
    for agent in &config.agents {
        let mut dep = match agent_patch_git_url(agent, registry) {
            Some(url) => {
                let mut table = InlineTable::new();
                table.insert("git", Value::from(url));
                table
            }
            None => source_to_inline_table(&agent.source),
        };
        if let Some(features) = &agent.crate_features {
            dep.insert("default-features", Value::from(false));
            let mut features_array = Array::new();
            for f in features {
                features_array.push(f.as_str());
            }
            dep.insert("features", Value::from(features_array));
        }

        deps.insert(&agent.name, Item::Value(Value::InlineTable(dep)));
    }

    Ok(())
}

/// For core/plugin: always emit a version string in [dependencies].
/// When the source is Path or Git, the actual override goes into [patch.crates-io].
fn dep_config_to_dep_value(dep_config: &DepConfig) -> Value {
    match &dep_config.source {
        AgentSource::Registry { version } => Value::from(version.as_str()),
        _ => Value::from(dep_config.default_version.as_str()),
    }
}

/// Canonical git URL for an agent whose local path should be expressed as a
/// [patch] entry. Returns `None` when the source goes inline into
/// [dependencies] (git/registry sources, or custom agents unknown to the
/// registry, which have no canonical URL to patch against).
fn agent_patch_git_url<'a>(agent: &AgentEntry, registry: &'a Registry) -> Option<&'a str> {
    if !matches!(agent.source, AgentSource::Path { .. }) {
        return None;
    }
    registry::find_by_name(&registry.agents, &agent.name).map(|k| k.git_url.as_str())
}

/// Build [patch.crates-io] for core/plugin overrides and [patch."<git-url>"]
/// for agents overridden with a local path.
fn update_patch_section(doc: &mut DocumentMut, config: &BuildConfig, registry: &Registry) {
    // Remove existing [patch] section first
    doc.remove("patch");

    let mut crates_io_table = Table::new();
    if !matches!(config.core.source, AgentSource::Registry { .. }) {
        crates_io_table.insert(
            "modular-agent-core",
            Item::Value(Value::InlineTable(source_to_inline_table(
                &config.core.source,
            ))),
        );
    }
    if !matches!(config.plugin.source, AgentSource::Registry { .. }) {
        crates_io_table.insert(
            "tauri-plugin-modular-agent",
            Item::Value(Value::InlineTable(source_to_inline_table(
                &config.plugin.source,
            ))),
        );
    }

    let git_patches: Vec<(&str, &AgentEntry)> = config
        .agents
        .iter()
        .filter_map(|agent| agent_patch_git_url(agent, registry).map(|url| (url, agent)))
        .collect();

    if crates_io_table.is_empty() && git_patches.is_empty() {
        return;
    }

    let comment = "\n# Local source overrides (generated by ma-config).\n\
                   # Delete these [patch] sections to build from the canonical sources above.\n";
    let mut commented = false;

    let mut patch_table = Table::new();
    patch_table.set_implicit(true);

    if !crates_io_table.is_empty() {
        crates_io_table.decor_mut().set_prefix(comment);
        commented = true;
        patch_table.insert("crates-io", Item::Table(crates_io_table));
    }

    for (url, agent) in git_patches {
        let item = patch_table.entry(url).or_insert(Item::Table(Table::new()));
        if let Some(table) = item.as_table_mut() {
            if !commented {
                table.decor_mut().set_prefix(comment);
                commented = true;
            }
            table.insert(
                &agent.name,
                Item::Value(Value::InlineTable(source_to_inline_table(&agent.source))),
            );
        }
    }

    doc.insert("patch", Item::Table(patch_table));
}

fn source_to_inline_table(source: &AgentSource) -> InlineTable {
    let mut dep = InlineTable::new();
    match source {
        AgentSource::Path { path } => {
            dep.insert("path", Value::from(normalize_path(path)));
        }
        AgentSource::Git { url, tag } => {
            dep.insert("git", Value::from(url.as_str()));
            if let Some(tag) = tag {
                dep.insert("tag", Value::from(tag.as_str()));
            }
        }
        AgentSource::Registry { version } => {
            dep.insert("version", Value::from(version.as_str()));
        }
    }
    dep
}

fn backup_file(path: &Path) -> Result<(), String> {
    if path.exists() {
        let backup = path.with_extension(format!(
            "{}.bak",
            path.extension().and_then(|e| e.to_str()).unwrap_or("bak")
        ));
        fs::copy(path, &backup).map_err(|e| format!("Failed to backup {}: {e}", path.display()))?;
    }
    Ok(())
}

pub fn cleanup_backups(tauri_root: &Path) {
    let path = tauri_root.join("Cargo.toml.toml.bak");
    let _ = fs::remove_file(path);
}

/// Normalize path separators: backslash -> forward slash for Cargo.toml compatibility.
fn normalize_path(path: &str) -> String {
    path.replace('\\', "/")
}

/// Validate that all Path sources exist on disk.
pub fn validate_paths(config: &BuildConfig, tauri_root: &Path) -> Vec<String> {
    let mut warnings = Vec::new();

    // Check core path
    if let AgentSource::Path { path } = &config.core.source {
        let full_path = tauri_root.join(path);
        if !full_path.join("Cargo.toml").exists() {
            warnings.push(format!(
                "modular-agent-core: path '{path}' does not contain a Cargo.toml"
            ));
        }
    }

    // Check plugin path
    if let AgentSource::Path { path } = &config.plugin.source {
        let full_path = tauri_root.join(path);
        if !full_path.join("Cargo.toml").exists() {
            warnings.push(format!(
                "tauri-plugin-modular-agent: path '{path}' does not contain a Cargo.toml"
            ));
        }
    }

    // Check agent paths
    for agent in &config.agents {
        if let AgentSource::Path { path } = &agent.source {
            let full_path = tauri_root.join(path);
            if !full_path.join("Cargo.toml").exists() {
                warnings.push(format!(
                    "{}: path '{path}' does not contain a Cargo.toml",
                    agent.name
                ));
            }
        }
    }
    warnings
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::registry::{DepDefaults, KnownAgent};

    fn test_registry() -> Registry {
        Registry {
            core: DepDefaults {
                default_path: "../../modular-agent-core/modular-agent-core".into(),
                git_url: "https://github.com/modular-agent/modular-agent-core.git".into(),
                default_version: "0.25.0".into(),
            },
            plugin: DepDefaults {
                default_path: "../../tauri-plugin-modular-agent".into(),
                git_url: "https://github.com/modular-agent/tauri-plugin-modular-agent.git".into(),
                default_version: "0.16.0".into(),
            },
            agents: vec![KnownAgent {
                name: "modular-agent-std".into(),
                description: "Standard agents".into(),
                git_url: "https://github.com/modular-agent/modular-agent-std.git".into(),
                available_features: vec![],
                default_features: vec![],
                conflicts: vec![],
                is_default: true,
            }],
        }
    }

    fn test_config() -> BuildConfig {
        BuildConfig {
            core: DepConfig {
                default_version: "0.25.0".into(),
                source: AgentSource::Path {
                    path: "../../modular-agent-core/modular-agent-core".into(),
                },
            },
            plugin: DepConfig {
                default_version: "0.16.0".into(),
                source: AgentSource::Registry {
                    version: "0.16.0".into(),
                },
            },
            agents: vec![
                AgentEntry {
                    name: "modular-agent-std".into(),
                    source: AgentSource::Path {
                        path: "../../modular-agent-std".into(),
                    },
                    crate_features: None,
                },
                AgentEntry {
                    name: "modular-agent-custom".into(),
                    source: AgentSource::Path {
                        path: "../../modular-agent-custom".into(),
                    },
                    crate_features: None,
                },
            ],
        }
    }

    #[test]
    fn local_paths_become_patches_not_dependency_rewrites() {
        let mut doc: DocumentMut = "[dependencies]\nserde = \"1\"\n\
             modular-agent-std = { path = \"stale\" }\n"
            .parse()
            .unwrap();
        let config = test_config();
        let registry = test_registry();

        update_dependencies(&mut doc, &config, &registry).unwrap();
        update_patch_section(&mut doc, &config, &registry);
        let out = doc.to_string();

        // Known agent keeps its canonical git URL in [dependencies]...
        assert!(out.contains(
            "modular-agent-std = { git = \"https://github.com/modular-agent/modular-agent-std.git\" }"
        ));
        // ...and its local path lives in a deletable [patch] section.
        assert!(
            out.contains("[patch.\"https://github.com/modular-agent/modular-agent-std.git\"]")
        );
        assert!(out.contains("modular-agent-std = { path = \"../../modular-agent-std\" }"));

        // Custom agent without a registry entry falls back to an inline path.
        assert!(out.contains("modular-agent-custom = { path = \"../../modular-agent-custom\" }"));

        // Core path override goes into [patch.crates-io]; version stays in deps.
        assert!(out.contains("[patch.crates-io]"));
        assert!(out.contains(
            "modular-agent-core = { version = \"0.25.0\", features = [\"mcp-server\"] }"
        ));

        // Plugin from crates.io needs no patch entry.
        assert!(!out.contains("tauri-plugin-modular-agent = { path"));
    }

    #[test]
    fn no_patch_section_when_everything_is_canonical() {
        let mut doc: DocumentMut = "[dependencies]\nserde = \"1\"\n\n[patch.crates-io]\n\
             modular-agent-core = { path = \"old\" }\n"
            .parse()
            .unwrap();
        let mut config = test_config();
        config.core.source = AgentSource::Registry {
            version: "0.25.0".into(),
        };
        config.agents = vec![AgentEntry {
            name: "modular-agent-std".into(),
            source: AgentSource::Git {
                url: "https://github.com/modular-agent/modular-agent-std.git".into(),
                tag: None,
            },
            crate_features: None,
        }];
        let registry = test_registry();

        update_dependencies(&mut doc, &config, &registry).unwrap();
        update_patch_section(&mut doc, &config, &registry);
        let out = doc.to_string();

        assert!(!out.contains("[patch"));
    }
}
