use std::fs;
use std::path::Path;

use toml_edit::{Array, DocumentMut, InlineTable, Item, Table, Value};

use crate::config::{AgentSource, BuildConfig, DepConfig};

/// Update `src-tauri/Cargo.toml` with the selected agents as dependencies.
pub fn update_cargo_toml(config: &BuildConfig, tauri_root: &Path) -> Result<(), String> {
    let cargo_path = tauri_root.join("Cargo.toml");
    let original =
        fs::read_to_string(&cargo_path).map_err(|e| format!("Failed to read Cargo.toml: {e}"))?;

    // Backup
    backup_file(&cargo_path)?;

    let mut doc: DocumentMut = original
        .parse()
        .map_err(|e| format!("Failed to parse Cargo.toml: {e}"))?;

    // Update dependencies
    update_dependencies(&mut doc, config)?;

    // Update [patch.crates-io] for core/plugin when using Path or Git
    update_patch_section(&mut doc, config);

    fs::write(&cargo_path, doc.to_string()).map_err(|e| format!("Failed to write Cargo.toml: {e}"))
}

/// Generate `src-tauri/src/agents.rs` with imports for each agent.
pub fn generate_agents_rs(config: &BuildConfig, tauri_root: &Path) -> Result<(), String> {
    let agents_path = tauri_root.join("src/agents.rs");

    let mut content = String::from(
        "//! Agent crate imports (auto-generated by ma-config, do not edit)\n\
         //!\n\
         //! Each `use` pulls in the crate, causing #[modular_agent] registrations\n\
         //! to be linked via the `inventory` crate.\n",
    );

    for agent in &config.agents {
        let crate_name = agent.rust_crate_name();
        content.push_str(&format!(
            "\n#[allow(unused_imports)]\n\
             use {crate_name};\n"
        ));
    }

    fs::write(&agents_path, content).map_err(|e| format!("Failed to write agents.rs: {e}"))
}

fn update_dependencies(doc: &mut DocumentMut, config: &BuildConfig) -> Result<(), String> {
    let deps = doc["dependencies"]
        .as_table_mut()
        .ok_or("Missing [dependencies] in Cargo.toml")?;

    // Remove all modular-agent-* and tauri-plugin-modular-agent deps
    let keys_to_remove: Vec<String> = deps
        .iter()
        .filter_map(|(key, _)| {
            if key.starts_with("modular-agent-") || key == "tauri-plugin-modular-agent" {
                Some(key.to_string())
            } else {
                None
            }
        })
        .collect();

    for key in keys_to_remove {
        deps.remove(&key);
    }

    // Add core — always as version string in [dependencies].
    // Path/Git override goes into [patch.crates-io].
    deps.insert(
        "modular-agent-core",
        Item::Value(dep_config_to_dep_value(&config.core)),
    );

    // Add plugin — same strategy as core.
    deps.insert(
        "tauri-plugin-modular-agent",
        Item::Value(dep_config_to_dep_value(&config.plugin)),
    );

    // Add selected agents
    for agent in &config.agents {
        let mut dep = source_to_inline_table(&agent.source);
        if let Some(features) = &agent.crate_features {
            dep.insert("default-features", Value::from(false));
            let mut features_array = Array::new();
            for f in features {
                features_array.push(f.as_str());
            }
            dep.insert("features", Value::from(features_array));
        }

        deps.insert(&agent.name, Item::Value(Value::InlineTable(dep)));
    }

    Ok(())
}

/// For core/plugin: always emit a version string in [dependencies].
/// When the source is Path or Git, the actual override goes into [patch.crates-io].
fn dep_config_to_dep_value(dep_config: &DepConfig) -> Value {
    match &dep_config.source {
        AgentSource::Registry { version } => Value::from(version.as_str()),
        _ => Value::from(dep_config.default_version.as_str()),
    }
}

/// Build [patch.crates-io] section for core and plugin when they use Path or Git.
fn update_patch_section(doc: &mut DocumentMut, config: &BuildConfig) {
    // Remove existing [patch] section first
    doc.remove("patch");

    let mut patches: Vec<(&str, &AgentSource)> = Vec::new();

    if !matches!(config.core.source, AgentSource::Registry { .. }) {
        patches.push(("modular-agent-core", &config.core.source));
    }
    if !matches!(config.plugin.source, AgentSource::Registry { .. }) {
        patches.push(("tauri-plugin-modular-agent", &config.plugin.source));
    }

    if patches.is_empty() {
        return;
    }

    // Build [patch.crates-io] table
    let mut crates_io_table = Table::new();
    for (name, source) in patches {
        crates_io_table.insert(
            name,
            Item::Value(Value::InlineTable(source_to_inline_table(source))),
        );
    }

    let mut patch_table = Table::new();
    patch_table.set_implicit(true);
    patch_table.insert("crates-io", Item::Table(crates_io_table));
    doc.insert("patch", Item::Table(patch_table));
}

fn source_to_inline_table(source: &AgentSource) -> InlineTable {
    let mut dep = InlineTable::new();
    match source {
        AgentSource::Path { path } => {
            dep.insert("path", Value::from(normalize_path(path)));
        }
        AgentSource::Git { url, tag } => {
            dep.insert("git", Value::from(url.as_str()));
            if let Some(tag) = tag {
                dep.insert("tag", Value::from(tag.as_str()));
            }
        }
        AgentSource::Registry { version } => {
            dep.insert("version", Value::from(version.as_str()));
        }
    }
    dep
}

fn backup_file(path: &Path) -> Result<(), String> {
    if path.exists() {
        let backup = path.with_extension(format!(
            "{}.bak",
            path.extension().and_then(|e| e.to_str()).unwrap_or("bak")
        ));
        fs::copy(path, &backup).map_err(|e| format!("Failed to backup {}: {e}", path.display()))?;
    }
    Ok(())
}

pub fn cleanup_backups(tauri_root: &Path) {
    let path = tauri_root.join("Cargo.toml.toml.bak");
    let _ = fs::remove_file(path);
}

/// Normalize path separators: backslash -> forward slash for Cargo.toml compatibility.
fn normalize_path(path: &str) -> String {
    path.replace('\\', "/")
}

/// Validate that all Path sources exist on disk.
pub fn validate_paths(config: &BuildConfig, tauri_root: &Path) -> Vec<String> {
    let mut warnings = Vec::new();

    // Check core path
    if let AgentSource::Path { path } = &config.core.source {
        let full_path = tauri_root.join(path);
        if !full_path.join("Cargo.toml").exists() {
            warnings.push(format!(
                "modular-agent-core: path '{path}' does not contain a Cargo.toml"
            ));
        }
    }

    // Check plugin path
    if let AgentSource::Path { path } = &config.plugin.source {
        let full_path = tauri_root.join(path);
        if !full_path.join("Cargo.toml").exists() {
            warnings.push(format!(
                "tauri-plugin-modular-agent: path '{path}' does not contain a Cargo.toml"
            ));
        }
    }

    // Check agent paths
    for agent in &config.agents {
        if let AgentSource::Path { path } = &agent.source {
            let full_path = tauri_root.join(path);
            if !full_path.join("Cargo.toml").exists() {
                warnings.push(format!(
                    "{}: path '{path}' does not contain a Cargo.toml",
                    agent.name
                ));
            }
        }
    }
    warnings
}
