//! Agent crate imports (auto-generated by ma-config, do not edit)
//!
//! Each `use` pulls in the crate, causing #[modular_agent] registrations
//! to be linked via the `inventory` crate.

use modular_agent_audio as _;

use modular_agent_lifelog as _;

use modular_agent_llm as _;

use modular_agent_monty as _;

use modular_agent_slack as _;

use modular_agent_sqlx as _;

use modular_agent_std as _;

use modular_agent_voicevox as _;

use modular_agent_web as _;
